import type { Metadata } from "next";
import * as React from "react";
import CssBaseline from "@mui/material/CssBaseline";
import Container from "@mui/material/Container";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<CssBaseline />
				<Container maxWidth="sm" id="outer-container" className="col">
					{children}
				</Container>
			</body>
		</html>
	);
}
